image: gitpod/workspace-full:latest
  
ports:
  - port: 4000
    onOpen: open-preview

tasks:
  - init: >
      bundle install
    command: >
      bundle exec jekyll serve --host 0.0.0.0 --config _config.yml
